apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.serviceName }}-service

spec:
  type: {{ .Values.typeOfService }}

  selector:
    app: {{ .Values.appName }}

  ports:
    - protocol: TCP
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.targetPort }}